firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path  
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls'))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstproject/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('create-post/', views.post_create, name="create-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

firstproject/users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
  path('register/',views.register_user, name='register'),
  path('login/',views.login_user, name='login'),
  path('logout/',views.logout_user, name='logout'),
]

firstproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=75)
  body = models.TextField()
  slug = models.SlugField()
  date = models.DateTimeField(auto_now_add=True)
  banner = models.ImageField(default='fallback.png',blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

  def __str__(self):
    return self.title

firstproject/users/models.py
from django.db import models

# Create your models here.

firstproject/posts/forms.py
from django import forms
from . import models
class CreatePost(forms.ModelForm):
  class Meta:
    model = models.Post
    fields = ['title','body','slug','banner']

firstproject/firstproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def home(request):
  # return HttpResponse("You're on the home page...")
  return render(request,'home.html')

def about(request):
  # return HttpResponse("You're on the about page...")
  return render(request,'about.html')

firstproject/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def posts_list(req):
  posts = Post.objects.all().order_by('-date')
  return render(req,'posts/posts_list.html',{'posts':posts})

def post_page(req,slug):
  post = Post.objects.get(slug=slug)
  return render(req,'posts/post_page.html',{'post':post})
  
@login_required(login_url='/users/login/')
def post_create(req):
  if req.method == "POST":
    form = forms.CreatePost(req.POST, req.FILES)
    if form.is_valid():
      newpost = form.save(commit=False)
      newpost.author = req.user
      newpost.save()
      return redirect("posts:list")
  else:
    form = forms.CreatePost()
  return render(req,'posts/post_create.html',{'form':form})

firstproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def register_user(req):
  if req.method == "POST":
    form = UserCreationForm(req.POST)
    if form.is_valid():
      login(req,form.save()) # this also returns the user so its valid
      return redirect("posts:list")
  else:
    form = UserCreationForm()
  
  return render(req,'users/register.html',{'form':form})

def login_user(req):
  if req.method =="POST":
    form = AuthenticationForm(data=req.POST)
    if form.is_valid():
      login(req,form.get_user())
      if 'next' in req.POST:
        return redirect(req.POST.get('next'))
      else:
        return redirect("posts:list")
  else:
    form = AuthenticationForm()
  
  return render(req,'users/login.html',{'form':form})

def logout_user(req):
  if req.method == "POST":
    logout(req)
    return redirect("posts:list")

firstproject/posts/templates/posts/post_create.html
{% extends "layout.html" %}

{% block title %}
Create a new post
{% endblock title %}

{% block content %}
  <section>
    <h1>Create post</h1>
    <form action="{% url "posts:create-post" %}" class="form-with-validation" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <button class="form-submit">Add post</button>
    </form>
  </section>
{% endblock content %}

firstproject/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
  <section>
    <img class="banner" src="{{post.banner.url}}" alt="{{post.title}}"/>
    <h2>{{ post.title }}</h2>
    <p class="date">{{ post.date }}</p>
    <p>{{ post.body }}</p>
  </section>
  
{% endblock content %}

firstproject/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
  Posts
{% endblock title %}

{% block content %}
  <section>
    <h2>Posts</h2>
    {% for post in posts %}
      <article class="post">
        <h3>
          <a href="{% url 'posts:page' slug=post.slug %}">{{ post.title }}</a>
        </h3>
        <p class="date">{{ post.date }} by {{ post.author }}</p>
        <p>{{ post.body }}</p>
      </article>
    {% endfor %}
  </section>
  
{% endblock content %}

firstproject/templates/about.html
{% extends "layout.html" %}

{% block title %}
  About
{% endblock %}

{% block content %}
  <h2>This is about page</h2>
  <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci odit libero excepturi enim veritatis quo tempore repellendus dolorem delectus quia, ratione placeat quisquam iste nesciunt facilis fugiat error sapiente quod optio est!</p>
{% endblock %}

firstproject/templates/home.html
{% extends "layout.html" %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <h2>This is a simple Django project</h2>
  <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci odit libero excepturi enim veritatis quo tempore repellendus dolorem delectus quia, ratione placeat quisquam iste nesciunt facilis fugiat error sapiente quod optio est!</p>
  <p>Link to <a href="/about">About</a> page </p>
{% endblock %}

firstproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Django App
    {% endblock %}
  </title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <nav>
    <a href="/">Home</a> |
    <a href="/about">About</a> |
    <a href="{% url 'posts:list' %}">Posts</a> |
    {% if user.is_authenticated %}
      <a href="{% url 'posts:create-post' %}">New</a> |
      <form class="logout" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button class="logout-button">Logout</button>
      </form>
    {% else %}
      <a href="{% url 'users:register' %}">Register user</a> |
      <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
  </nav>
  <main>
    {% block content %}

    {% endblock %}
  </main>
</body>
</html>

firstproject/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
  User login
{% endblock title %}

{% block content %}
  <h2>User login</h2>
  <form class="form-with-validation" action="{% url 'users:login' %}" method='post'>
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    {% endif %}
    <button class="form-submit">Submit</button>
  </form>
  
{% endblock content %}

firstproject/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
  Register a new user
{% endblock title %}

{% block content %}
  <h2>Register a new user</h2>
  <form class="form-with-validation" action="{% url 'users:register' %}" method='post'>
    {% csrf_token %}
    {{form}}
    <button class="form-submit">Submit</button>
  </form>
  
{% endblock content %}